//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Tree Analyser.rc
//
#define IDBROWSE                        3
#define ID_ADD_CAMERA                   3
#define ID_VIEW_CAMERA_INFO             5
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TREEANALYSER_DIALOG         102
#define IDS_LAST_UPDATE                 102
#define IDS_VERSION                     103
#define IDR_HTML_INPUTDLG               104
#define IDS_COPYRIGHT                   104
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDD_DLG_ADD_IMAGE               130
#define IDD_DLG_PROGRAM_SET             138
#define IDD_PICTURE_COMBINATION         144
#define IDD_DLG_INPUT                   158
#define IDD_DLG_ADVANCE                 159
#define IDI_ICON2                       165
#define IDD_DLG_CAPTURE                 168
#define IDD_CAPTRUE_DLG                 171
#define IDB_PIAF                        172
#define IDB_KU                          173
#define IDD_DLG_COMPARE_CANOPY          175
#define IDD_DLG_EXPORT_BEAMS            176
#define IDD_DIALOG1                     177
#define IDD_DLG_ADD_CAMERA              177
#define IDC_TREE1                       1000
#define IDC_OUTPUT                      1002
#define IDC_EDIT_FNAME                  1005
#define IDC_EDIT_DISTANCE               1006
#define IDC_COMBO_CAMERA                1007
#define IDC_EDIT_HEIGHT                 1008
#define IDC_EDIT_DIRECTION              1009
#define IDC_EDIT_INC                    1010
#define IDC_EDIT_AZ                     1011
#define IDC_EDIT_BENDING                1011
#define IDC_EDIT_ROT                    1012
#define IDC_EDIT_FOCAL                  1013
#define IDC_PICTYPE                     1014
#define IDC_EDIT_PICH                   1015
#define IDC_EDIT_PICNAME                1016
#define IDC_EDIT_PICW                   1017
#define IDC_EDIT_CCDSIZE                1018
#define IDC_EDIT_CURVE                  1019
#define IDC_EDIT_CCDPERCENT             1020
#define IDC_COMBO_DIRECTION             1020
#define IDC_RADIO2                      1021
#define IDC_btnBrowse                   1022
#define IDC_RADIO7                      1022
#define IDC_EDIT_VIEWANGLE              1023
#define IDC_LIST1                       1023
#define IDC_btnCapture                  1024
#define IDC_Pic                         1025
#define IDC_EDIT_OUTPUT                 1026
#define IDC_IMAGE_PROPERTIES            1027
#define IDC_EDIT_IMAGE                  1028
#define IDC_SETTING_PROPERTIES          1028
#define IDC_BTN_IMAGE                   1029
#define IDC_EDIT_CELLSIZE_X             1034
#define IDC_EDIT_CELLSIZE_Y             1035
#define IDC_EDIT_CELLSIZE_Z             1036
#define IDC_EDIT_ENLARGER               1037
#define IDC_EDIT_RAYPX                  1038
#define IDC_STATUS_BAR                  1039
#define IDC_EDIT_RAYPY                  1039
#define IDC_EDIT_RAYPX2                 1040
#define IDC_EDIT_RAYPY2                 1041
#define IDC_CHECK_BOX                   1042
#define IDC_CHECK_SKELETON              1043
#define IDC_CHECK_VOLUMELOG             1043
#define IDC_BTN_DEFAULT                 1044
#define IDC_RADIO1                      1045
#define IDC_RADIO3                      1046
#define IDC_RADIO4                      1047
#define IDC_EDIT1                       1048
#define IDC_MA                          1048
#define IDC_CHECK1                      1049
#define IDC_RADIO_AUTOCLUMP             1049
#define IDC_EDIT5                       1049
#define IDC_CHECK2                      1050
#define IDC_EDIT_NUM                    1050
#define IDC_RADIO_CUSTOMCLUMP           1050
#define IDC_MIN_FC                      1050
#define IDC_CHECK3                      1051
#define IDC_MAX_FC                      1051
#define IDC_EDIT2                       1052
#define IDC_DISTRIBUTION_FILE           1052
#define IDC_INPUT                       1052
#define IDC_EDIT_MAXLAD                 1052
#define IDC_DATE                        1052
#define IDC_CHECK4                      1053
#define IDC_OWNER                       1053
#define IDC_EDIT_RAYPX3                 1054
#define IDC_EDIT_ENLARGER2              1055
#define IDC_NOTE                        1055
#define IDC_EDIT_RAYPY3                 1056
#define IDC_CHECK5                      1057
#define IDC_COMBO_LDISTRIBUTION         1058
#define IDC_EDIT3                       1059
#define IDC_EDIT_CLUMP                  1059
#define IDC_EDIT4                       1060
#define IDC_CHECK6                      1061
#define IDC_EDIT6                       1061
#define IDC_COMBO2                      1062
#define IDC_G_SPHERICAL                 1063
#define IDC_DEG                         1064
#define IDC_BROWSE                      1065
#define IDC_Txt_Instruction             1066
#define IDC_Txt_Unit                    1067
#define IDC_BUTTON_ADVANCE              1068
#define IDC_EDIT_ELE                    1069
#define IDC_CHK_SET_LAD                 1072
#define IDC_TXT_UPDATE                  1075
#define IDC_TXT_VERSION                 1076
#define IDC_TXT_COPYRIGHT               1077
#define IDC_RADIO5                      1078
#define IDC_RADIO6                      1079
#define IDC_EDIT_GPX                    1080
#define IDC_EDIT_GPY                    1081
#define IDC_EDIT_LAPX                   1082
#define IDC_RADIO_PZA                   1082
#define IDC_EDIT_LAPY                   1083
#define IDC_EDIT_PZA                    1083
#define IDC_COMBO3                      1085
#define IDC_RADIO_NOCLUMP               1086
#define IDC_BUTTON2                     1088
#define IDC_WEBCAM                      1090
#define IDC_CaptureBtn                  1094
#define IDC_ImageFrame                  1095
#define IDC_BROWSE1                     1097
#define IDC_BROWSE2                     1098
#define IDC_CHK_LAD                     1099
#define IDC_BUTTON1                     1100
#define IDC_INRA_WEB                    1101
#define IDC_KU_WEB                      1102
#define IDC_KU_LOGO                     1103
#define IDC_PIAF_LOGO                   1104
#define IDC_MAIL_TO_JESSADA             1105
#define IDC_MAIL_TO_SINOQUET            1106
#define IDC_MAIL_TO_TREEANALYSER        1107
#define IDC_EDIT_OUTPUT_DIRECTORY       1108
#define IDC_EDIT_FILENAME               1109
#define IDC_CHECK_PYTHON_OUT            1110
#define IDC_ONE_FILE                    1111
#define IDC_MODEL                       1112
#define IDC_CALIBRATION_VALUE           1113
#define IDC_PY_VERSION                  1114
#define IDC_Btn_SetPZA                  1115
#define ID_FILE_OPENPROJECT             32772
#define ID_FILE_SAVEPROJECT             32773
#define ID_FILE_EXIT                    32775
#define ID_PROJECT_SETTING              32777
#define ID_PROJECT_ANALYSIS             32778
#define ID_PROJECT_VOLUME               32778
#define ID_PROJECT_RECONSTRUCTION       32779
#define ID_PROJECT_RATP                 32780
#define ID_PROJECT_EXPORTDATA           32781
#define ID_HELP_ABOUT                   32782
#define ID_IMAGE_SAVEPIXELVALUE         32783
#define ID_IMAGE_ADDGRID                32785
#define ID_IMAGE_CALCUALTEGAPFRACTION   32786
#define ID_IMAGE_EDITPARAMETERS         32787
#define ID_IMAGE_DELETE                 32792
#define ID_FILE_SETTING                 32793
#define ID_FILE_1                       32794
#define ID_FILE_2                       32795
#define ID_FILE_3                       32796
#define ID_FILE_4                       32797
#define ID_PROJECT_ESTIMATETREEDIMENSION 32798
#define ID_IMAGE_REGISTERIMAGE          32802
#define ID_PROJECT_ANALYSEALL           32803
#define ID_TEST_TEST                    32804
#define ID_Menu                         32808
#define ID_TEST_TESTUNITVECTOR          32812
#define ID_Menu32814                    32814
#define ID_CANOPY_DISPLAYPROPERTIES     32815
#define ID_Menu32816                    32816
#define ID_TEST_TESTFUNCTION            32817
#define ID_IMAGE_MARKALL                32818
#define ID_IMAGE_UNMARKALL              32819
#define ID_IMAGE_TOGLEMARK              32820
#define ID_CANOPY_SAVECANOPY            32821
#define ID_CANOPY_OPENCANOPY            32822
#define ID_IMAGE_FRACTALANALYSIS        32823
#define ID_CANOPY_RUNRATP               32824
#define ID_IMAGE_COLORCOUNTING          32825
#define ID_CANOPY_RANDOMLEAFINVOLUME    32826
#define ID_CANOPY_DECREASE              32829
#define ID_CANOPY_RERUNRAY              32830
#define ID_Menu32831                    32831
#define ID_PROJECT_LA_TOTAL             32833
#define ID_PROJECT_LA_INTERCEPTED       32834
#define ID_FILE_NEWPROJECT              32835
#define ID_PROJECT_COMPUTELADDISTRIBUTION 32836
#define ID_TEST_1                       32837
#define ID_TEST1                        32839
#define ID_TEST2                        32840
#define ID_CANOPY_COMPARECANOPY         32841
#define ID_CANOPY_EXPORTVEGESTARCANOPY  32842
#define ID_TEST_TEST6                   32843
#define ID_CANOPY_VERTICALPROFILEOFLEAFAREA 32844
#define ID_CANOPY_EXPORTRATPVOXELS      32845
#define ID_TEST_SOLVINGEQUATION         32846
#define ID_CANOPY_VERTICALPROFILEOFVOLUME 32847
#define ID_TEST_SOLVINGLINEARREGRESSION 32848
#define ID_TEST_COMPUTEP0BEER           32849
#define ID_CANOPY_VIEWBYPLANTGL3DVIEWER 32850
#define ID_CANOPY_EXPORTPLANTGLFILE     32851
#define ID_VIEW_MARGINMARK              32853
#define ID_VIEW_CLEAROUTPUT             32854
#define ID_IMAGE_ADDIMAGETOPROJECT      32855
#define ID_VIEW_CENTERMARK              32857
#define ID_HELP_TREEANALYSERUSERMANUAL  32858
#define ID_TEST_EXPORTCSVFILEOFP0BINOM  32860
#define ID_CANOPY_EXPORTBEAMEQUATIONS   32861
#define ID_CALCULATION_EXPORTEQUATIONSFORPYTHON 32862
#define ID_TEST_CHECKVRESION            32863
#define ID_HELP_VERSIONHISTORY          32864

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32865
#define _APS_NEXT_CONTROL_VALUE         1116
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
